"""
v0.2 declarative part spec system.

A spec is a JSON document declaring a SOLIDWORKS part as an ordered list of
features. The build executor walks the features in order, calls the matching
SW COM API for each one, and reports a manifest describing what was built.

Submodules:
- schema   : the JSON schema (single source of truth for spec format)
- validator: schema + dependency-graph + locals.txt var-reference checks
- builder  : direct-COM build executor (one function per feature type)
- manifest : structured diff between spec intent and resulting SW state
"""

from pathlib import Path

from .schema import SCHEMA, SCHEMA_VERSION
from .validator import validate, ValidationError

__all__ = [
    "SCHEMA",
    "SCHEMA_VERSION",
    "validate",
    "ValidationError",
    "published_schema_path",
]


def published_schema_path() -> Path:
    """Filesystem path to the packaged published spec JSON Schema.

    Resolves the in-wheel copy of ``ai-sw-bridge.spec.schema.json`` (shipped as
    package data under ``ai_sw_bridge/schema/``) via ``importlib.resources``, so
    it works from a repo clone AND a pip/pipx/installer install where the
    repo-root ``schema/`` tree is not on disk. The returned file is byte-identical
    to the repo-root canonical copy -- both are generated by
    ``tools/emit_spec_schema.py`` and gated in sync. Point an editor's workspace
    schema mapping at this path to author ``spec.json`` files outside the repo.
    """
    from importlib.resources import files

    resource = files("ai_sw_bridge") / "schema" / "ai-sw-bridge.spec.schema.json"
    return Path(str(resource))
