#!/usr/bin/env python3
"""Canonical UTM-tagged launch links for the Project B launch kit.

Single source of truth for every outbound link in the launch copy, so the
mindshare funnel is measurable (spec §3, finding F8). Each channel maps to a
fixed (utm_source, utm_medium, utm_content) triple; the campaign and base URL
are parameters, so the github.io default can become a custom domain with one
flag and zero copy edits.

Run from repo root::

    python tools/launch_links.py
    python tools/launch_links.py --base-url https://ai-sw-bridge.example/

Exit 0 on success.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_BASE_URL = "https://thomas-tai.github.io/ai-sw-bridge/"
DEFAULT_CAMPAIGN = "launch"
DEFAULT_OUT = "launch-kit/utm_links.md"

# channel key -> (utm_source, utm_medium, utm_content)
CHANNELS: dict[str, tuple[str, str, str]] = {
    "show-hn": ("news.ycombinator.com", "referral", "show-hn"),
    "x": ("x.com", "social", "launch-thread"),
    "linkedin": ("linkedin.com", "social", "launch-article"),
    "reddit-solidworks": ("reddit.com", "social", "r-solidworks"),
    "reddit-mcp": ("reddit.com", "social", "r-mcp"),
    "product-hunt": ("producthunt.com", "referral", "launch"),
    "mcp-registry": ("mcp-registry", "referral", "listing"),
}


def build_utm_url(
    base_url: str,
    source: str,
    medium: str,
    campaign: str,
    content: str | None = None,
) -> str:
    """Return *base_url* with utm_* params merged in (existing query kept)."""
    parts = urlsplit(base_url)
    query = dict(parse_qsl(parts.query))
    query["utm_source"] = source
    query["utm_medium"] = medium
    query["utm_campaign"] = campaign
    if content:
        query["utm_content"] = content
    return urlunsplit(
        (parts.scheme, parts.netloc, parts.path, urlencode(query), parts.fragment)
    )


def canonical_links(
    base_url: str = DEFAULT_BASE_URL,
    campaign: str = DEFAULT_CAMPAIGN,
) -> dict[str, str]:
    """Return {channel: utm_url} for every launch channel."""
    return {
        channel: build_utm_url(base_url, src, med, campaign, content)
        for channel, (src, med, content) in CHANNELS.items()
    }


def render_manifest(links: dict[str, str]) -> str:
    """Render channel->url as a markdown table (a generated file)."""
    lines = [
        "<!-- GENERATED by tools/launch_links.py — do not edit by hand. -->",
        "# Canonical launch links (UTM-tagged)",
        "",
        "| Channel | Link |",
        "|---|---|",
    ]
    for channel in sorted(links):
        lines.append(f"| `{channel}` | {links[channel]} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate UTM launch links.")
    parser.add_argument("--base-url", default=DEFAULT_BASE_URL)
    parser.add_argument("--campaign", default=DEFAULT_CAMPAIGN)
    parser.add_argument("--out", default=DEFAULT_OUT)
    args = parser.parse_args()

    links = canonical_links(args.base_url, args.campaign)
    out_path = REPO_ROOT / args.out
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_manifest(links) + "\n", encoding="utf-8")
    print(f"OK: wrote {len(links)} links to {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
